# Authored by Anurag kumar
apiVersion: v1
kind: Service
metadata:
  name: data-collect-atlan
  labels:
    app: at-ba
    cloud: gcp
    datacenter: primary
    env: prod
    org: atlan
    pod: backend
    region: asia-south1
    tier: t1
  annotations:
    cloud.google.com/load-balancer-type: Internal
  namespace: backend-assignment
spec:
  type: LoadBalancer
  selector:
    app: data-collect-atlan
  ports:
    - port: 80
      targetPort: 8000
